### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by volkankoc** [masifdevs/Medical-Appointment#1]
You used flutter version ?
You used grandle version ?
You user kotlin version ?

my flutter version 3.3.1

**Comment by masifdevs** [comment]
I have worked on it in 2021   versions i used are: dart: ">=2.13.0 <3.0.0" flutter: ">=2.2.0" kotlin_version = '1.3.50' gradle:3.4.3

**Comment by volkankoc** [comment]
ok. 
Can you update with flutter version 3.
I need this ,
please

**Comment by volkankoc** [comment]
Please help me?

**Comment by masifdevs** [comment]
what issue you are facing?

**Comment by volkankoc** [comment]
The plugin `advance_pdf_viewer` uses a deprecated version of the Android embedding.
To avoid unexpected runtime failures, or future build failures, try to see if this plugin supports the Android V2 embedding. Otherwise, consider removing it since a future release of Flutter will remove these deprecated APIs.
If you are plugin author, take a look at the docs for migrating the plugin to the V2 embedding: https://flutter.dev/go/android-plugin-migration.

--------------

Note: /home/volkan/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/advance_pdf_viewer-2.0.0/android/src/main/java/pt/tribeiro/flutter_plugin_pdf_viewer/FlutterPluginPdfViewerPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
: Error: Member not found: 'packageRoot'.
../…/interface/local_platform.dart:46
      io.Platform.packageRoot; // ignore: deprecated_member_use
                  ^^^^^^^^^^^
2

FAILURE: Build failed with an exception.

* Where:
Script '/home/volkan/snap/flutter/common/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 1159

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command '/home/volkan/snap/flutter/common/flutter/bin/flutter'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 9s
Exception: Gradle task assembleDebug failed with exit code 1
Exited (sigterm)

**Comment by volkankoc** [comment]
i make minsdk 23 
I  have error

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':agora_rtc_engine:compileDebugKotlin'.
> Could not resolve all artifacts for configuration ':agora_rtc_engine:debugCompileClasspath'.
   > Could not find native-full-sdk.jar (com.github.agorabuilder:native-full-sdk:3.4.6).
     Searched in the following locations:
         https://www.jitpack.io/com/github/agorabuilder/native-full-sdk/3.4.6/native-full-sdk-3.4.6.jar

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 9s
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by volkankoc** [comment]
Can you compile the application with updated packages and add it again?

**Comment by masifdevs** [comment]
Dear to run this you have to download flutter old version.
